document.contact.name.onkeypress=function(){
    document.getElementById('namealert').innerHTML="";
}
document.contact.email.onkeypress=function(){
    document.getElementById('emailalert').innerHTML="";
}
document.contact.phone.onkeypress=function(){
    document.getElementById('phonealert').innerHTML="";
}
document.contact.message.onkeypress=function(){
    document.getElementById('messagealert').innerHTML="";
}